### ISSUE TITLE
setup.py fails despite genpackagedoc and pythonextensionscollection are in dependency list

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/python-genpackagedoc#43]
setup.py fails despite genpackagedoc and pythonextensionscollection are in dependency list.

Looks like that startup of setup.py fails due to importing libraries before they are installed in a system.
Todo: import after processing dependencies.

Reproduce:
unsintall genpackagedoc and pythonextensionscollection.
setup.py should fail

https://github.com/test-fullautomation/python-pytestlog2db/actions/runs/4819342881/jobs/8582422660

**Comment by ngoan1608** [comment]
Hi Thomas,
Hi Holger,

From my point of view, `genpackagedoc `and `pythonextensionscollection` are dependencies for building and installing packages than the package's dependencies (be defined in `install_requires` of setuptool).

Without `genpackagedoc `and `pythonextensionscollection`, tools/libraries such as PyTestLog2DB still works fine.
Package can be installed via `pip` (already built package) and works properly from user side.

Please correct me in case I misunderstood.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,

as discussed the following is O.K. for me:
1. ```genpackagedoc```and ```pythonextensionscollection``` are only dependencies of the build process. Therefore they are dependency in the build scripts.
2. dependencies for the build process need to be documented in a ```contribution chapter``` of for each repository.
3. all other dependencies must be part of the ```setup.py``` dependency list.
4. installation from pip must run without issue for all components (from our repositories)

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Holger,
this can be closed, correct?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

yes, can be closed.
