### ISSUE TITLE
Dependency clarification wanted

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/python-genpackagedoc#46]
I do not understand

https://github.com/test-fullautomation/python-genpackagedoc/pull/44

Why is the `PythonExtensionsCollection` added to the `INSTALLREQUIRES` now?

`"INSTALLREQUIRES" : ["pypandoc","colorama","PythonExtensionsCollection"],`

`GenPackageDoc` is the only component who does not have this dependency - because the `PythonExtensionsCollection` is part of `GenPackageDoc` (see `additions\PythonExtensionsCollection`).

In the past the `PythonExtensionsCollection` has been added to `GenPackageDoc` to avoid this dependency and make `GenPackageDoc` standalone.

**Comment by test-fullautomation** [comment]
Hi Holger,
my mistake, I overlooked this when I merged the Pull-Request.
I will correct this.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,
Hi Holger,

Please keep it.
I will explain more detail in our meeting.

Thank you

**Comment by test-fullautomation** [comment]
Hi Ngoan,

O.K. Holger searches a solution as per our discussion.

Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi Holger,
this can be closed, correct?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,

yes, it's clarified.
