### ISSUE TITLE
packagedoc_config.tmp file issue when run setup for genpackagedoc on Linux

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/python-genpackagedoc#57]
Hi Holger,

I ran the build pipeline this morning a faced below issue on Linux:
https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/5195920764/jobs/9369119212

It seems a side-effect of merged PR https://github.com/test-fullautomation/python-genpackagedoc/pull/55

Thank you,
Ngoan

**Comment by HolQue** [comment]
Hi Ngoan,

yes, you are right. Yesterday I observed the same on my machine.

Fix already available:

https://github.com/test-fullautomation/python-genpackagedoc/pull/56

**Comment by test-fullautomation** [comment]
solved and already merged with #56
